version: '1.0'

volumes:
    beautysaloonsqldata:
    identitysqldata:


networks:
    beautysaloon-network:
        external: true

services:
    beautysaloondata:
        container_name: BeautysaloonSQLServer
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=BeautysaloonSQLServer123
        volumes:
            - beautysaloonsqldata:/var/opt/mssql
        networks:
            - beautysaloon-network

    identitydata:
        container_name: BeautysaloonIdentitySQLServer
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1133:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=BeautysaloonIdentitySQLServer123
        volumes:
            - identitysqldata:/var/opt/mssql
        networks:
            - beautysaloon-network

    identity:
        container_name: beautysaloon-identity
        image: beautysaloon-identity-service:1.121
        build:
            dockerfile: ./BeautySaloon.Identity/Dockerfile
        ports:
            - "5010:80"
            - "5001:443"
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=DoctorHouse2001
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/aspnetapp.pfx
            - ConnectionStrings__BeautysaloonIdentityDbConnection=Server=BeautysaloonIdentitySQLServer;Initial Catalog=BeautySaloonDb; MultipleActiveResultSets=True; TrustServerCertificate=true; User Id = sa; Password = BeautysaloonIdentitySQLServer123;
        restart: on-failure
        networks:
            - beautysaloon-network
        depends_on:
            - identitydata
        volumes:
            - ./certs:/app/certs:ro

    beautysaloon:
        container_name: beautysaloon
        image: beautysaloon-service:1.2
        build:
            dockerfile: ./BeautySaloon.API/Dockerfile
        ports:
            - "5002:80"
        environment:
            - ConnectionStrings__BeautysaloonDbConnection=Server=BeautysaloonSQLServer;Initial Catalog=BeautySaloonDb; MultipleActiveResultSets=True; TrustServerCertificate=true; User Id = sa; Password = BeautysaloonSQLServer123;
        restart: on-failure
        networks:
            - beautysaloon-network
        depends_on:
            - beautysaloondata
